### PR TITLE
Update main.cpp

### PR DESCRIPTION
**Pull request by ASakrak**
pullrequest learrning test LMAO

### CODE REVIEW

**Comment by Benjino16** [comment]
nice, very good

**Comment by ASakrak** [comment]
thank you for comment freund ❤️

**Comment by Benjino16** [comment]
> a_n=1/(2^(n-1)n!)sum_(k=0)^(|_n/2_|)(-1)^k(n; k)(n-2k)^(n-1)sin[(n-2k)M]

nice math, i like it

**Comment by ASakrak** [comment]
> > a_n=1/(2^(n-1)n!)sum_(k=0)^(|_n/2_|)(-1)^k(n; k)(n-2k)^(n-1)sin[(n-2k)M]
> 
> nice math, i like it

Ja

**Pull request merged**
